apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
 name: platform-team-guest-binding
roleRef:
 kind: ClusterRole
 name: read-only-role
 apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
 name: platform-team-guest
 apiGroup: rbac.authorization.k8s.io
