apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
 name: platform-team-binding
roleRef:
 kind: ClusterRole
 name: read-write-role
 apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
 name: platform-team
 apiGroup: rbac.authorization.k8s.io
