apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  namespace: dev-buddy
  name: dev-buddy-admin-binding
roleRef:
  kind: Role
  name: dev-buddy-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
 - kind: User
   name: project-admin
   apiGroup: rbac.authorization.k8s.io
