apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  namespace: dev-buddy
  name: dev-buddy-dev-binding
roleRef:
  kind: Role
  name: dev-buddy-rw
  apiGroup: rbac.authorization.k8s.io
subjects:
 - kind: User
   name: project-lead
   apiGroup: rbac.authorization.k8s.io
