apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  namespace: dev-buddy
  name: dev-buddy-guest-binding
roleRef:
  kind: Role
  name: dev-buddy-ro
  apiGroup: rbac.authorization.k8s.io
subjects:
 - kind: User
   name: project-guest
   apiGroup: rbac.authorization.k8s.io
