apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  namespace: dev-buddy
  name: dev-buddy-deploy-binding
roleRef:
  kind: Role
  name: dev-buddy-deploy
  apiGroup: rbac.authorization.k8s.io
subjects:
 - kind: User
   name: project-deploy
   apiGroup: rbac.authorization.k8s.io
