apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-buddy-ro
  namespace: dev-buddy
  label:
    createdThrough: gitops
rules:
- apiGroups:
  - ""
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
